const board=document.querySelector('#board'),status=document.querySelector('#status'),dice=document.querySelector('#dice'),roll=document.querySelector('#roll');
const colors=['red','green','yellow','blue'];let turn=0,busy=false;
const path=[];for(let c=1;c<14;c++)path.push([6,c]);for(let r=7;r<14;r++)path.push([r,13]);for(let c=12;c>=0;c--)path.push([13,c]);for(let r=12;r>=8;r--)path.push([r,1]);for(let c=0;c<6;c++)path.push([8,c]);for(let r=7;r>=0;r--)path.push([r,0]);for(let c=1;c<14;c++)path.push([0,c]);for(let r=1;r<6;r++)path.push([r,13]);for(let c=14;c>8;c--)path.push([6,c]);
const starts=[0,13,26,39];const pieces=colors.map(()=>Array(4).fill(-1));
function key(r,c){return r*15+c}function render(){
 board.innerHTML='';for(let r=0;r<15;r++)for(let c=0;c<15;c++){const x=document.createElement('div');x.className='cell';if(r<6&&c<6)x.classList.add('red');else if(r<6&&c>8)x.classList.add('green');else if(r>8&&c>8)x.classList.add('yellow');else if(r>8&&c<6)x.classList.add('blue');if(path.some(p=>p[0]===r&&p[1]===c))x.style.background='#fff';board.appendChild(x)}
 pieces.forEach((ps,ci)=>ps.forEach((p,pi)=>{let rc;if(p<0){const homes=[[[1,1],[1,4],[4,1],[4,4]],[[1,10],[1,13],[4,10],[4,13]],[[10,10],[10,13],[13,10],[13,13]],[[10,1],[10,4],[13,1],[13,4]]];rc=homes[ci][pi]}else rc=path[(starts[ci]+p)%path.length];const cell=board.children[key(...rc)];const q=document.createElement('button');q.className='piece '+colors[ci];q.title=colors[ci];if(ci===0&&turn===0)q.addEventListener('click',()=>moveHuman(pi));cell.appendChild(q)}))
}
let last=0;function moveHuman(i){if(busy||turn!==0)return;const p=pieces[0][i];if(p<0&&last!==6)return;if(p<0)pieces[0][i]=0;else pieces[0][i]+=last;render();busy=true;setTimeout(next,500)}
function next(){turn=(turn+1)%4;busy=false;status.textContent=turn===0?'Tu turno · rojo.':'Turno de '+['','verde','amarillo','azul'][turn]+'.';if(turn!==0)setTimeout(bot,650)}
function bot(){const v=1+Math.floor(Math.random()*6);dice.textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][v-1];const hand=pieces[turn];let i=hand.findIndex(p=>p>=0);if(i<0&&v===6)i=0;if(i>=0){if(hand[i]<0)hand[i]=0;else hand[i]+=v}render();setTimeout(next,650)}
roll.addEventListener('click',()=>{if(busy||turn!==0)return;last=1+Math.floor(Math.random()*6);dice.textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][last-1];status.textContent='Sacaste '+last+'. Toca una ficha roja válida.';if(!pieces[0].some(p=>p>=0)&&last!==6){busy=true;setTimeout(next,800)}});render();