const centerOverlay=document.querySelector('.center');
const board=document.querySelector('#board'),status=document.querySelector('#status'),diceEls=[...document.querySelectorAll('[data-die]')].sort((a,b)=>Number(a.dataset.die)-Number(b.dataset.die));
const colors=['red','green','yellow','blue'],names=['Rojo','Verde','Amarillo','Azul'];
const path=[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
const starts=[0,13,26,39],safe=new Set([0,8,13,21,26,34,39,47]);
const BOARD_SIZE=15,HOME_CELLS=5;
const rotateCell=([r,c])=>[c,BOARD_SIZE-1-r];
// Five visible home squares followed by the finishing position inside the center.
const redLane=Array.from({length:HOME_CELLS+1},(_,i)=>[7,i+1]);
const lanes=[redLane];
for(let ci=1;ci<4;ci++)lanes.push(lanes[ci-1].map(rotateCell));

const homes=[[[2,2],[2,4],[4,2],[4,4]],[[2,10],[2,12],[4,10],[4,12]],[[10,10],[10,12],[12,10],[12,12]],[[10,2],[10,4],[12,2],[12,4]]];
const pips={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]};
let dragging=null;
let pieces=colors.map(()=>Array(4).fill(-1)),humanColor=0,turn=0,started=false,phase='idle',last=0,selectedTier=null,clock=null,seconds=10,sixes=0,generation=0;
function randomDie(){const a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=4294967292);return a[0]%6+1}
function showDie(n,el){el.innerHTML='<span class="cube">'+[n,7-n,...[1,2,3,4,5,6].filter(v=>v!==n&&v!==7-n)].map((v,i)=>'<span class="cube-face face-'+i+'"><span class="diceface">'+pips[v].map(p=>'<i class="pip p'+p+'"></i>').join('')+'</span></span>').join('')+'</span>'}
function position(ci,p,pi){return p<0?homes[ci][pi]:p<=50?path[(starts[ci]+p)%52]:lanes[ci][p-51]}
function legal(ci,v){return pieces[ci].map((p,i)=>p<0?v===6?i:-1:p<56&&p+v<=56?i:-1).filter(i=>i>=0)}
function render(){document.querySelectorAll('.home-well .piece').forEach(el=>el.remove());board.innerHTML='';board.style.setProperty('--board-cells',String(BOARD_SIZE));for(let r=0;r<BOARD_SIZE;r++)for(let c=0;c<BOARD_SIZE;c++){const el=document.createElement('div');el.className='cell';el.dataset.row=String(r);el.dataset.col=String(c);const ci=r<6&&c<6?0:r<6&&c>8?1:r>8&&c>8?2:r>8&&c<6?3:-1;if(ci>=0){el.classList.add(colors[ci],'yard');if(((r%9)>=1&&(r%9)<=4)&&((c%9)>=1&&(c%9)<=4))el.classList.add('yard-inner')}const track=path.findIndex(([a,b])=>a===r&&b===c);if(safe.has(track)){el.classList.add('safe');el.textContent='★'}starts.forEach((s,i)=>{if(track===s)el.classList.add(colors[i])});lanes.forEach((lane,i)=>{const step=lane.findIndex(([a,b])=>a===r&&b===c);if(step>=0){el.classList.add(colors[i]);if(step<HOME_CELLS){el.classList.add('home-lane');el.dataset.homeStep=String(step+1)}}});board.append(el)}board.append(centerOverlay);const counts={};pieces.forEach((hand,ci)=>hand.forEach((p,pi)=>{const [r,c]=position(ci,p,pi),cell=board.children[r*15+c],el=document.createElement('button');el.dataset.pawn=String(pi);el.className='piece '+colors[ci]+(p<0?' in-yard':'');el.innerHTML='<span class="pawn-art"><img src="assets/ludo-pawns-standing.webp?v=25" alt="" draggable="false"></span>';el.setAttribute('aria-label',names[ci]+' ficha '+(pi+1));const k=r*15+c,n=counts[k]||0;counts[k]=n+1;el.style.transform='translate('+((n%2)*7)+'px,'+(-Math.floor(n/2)*6)+'px)';const can=started&&phase==='move'&&ci===humanColor&&turn===ci&&legal(ci,last).includes(pi);el.disabled=!can;if(can)el.classList.add('movable');el.onclick=()=>{if(!el.dataset.dragged)move(pi)};if(can)enableDrag(el,ci,pi);if(p<0){const slotData=[{x:[.34,.68],y:[.32,.635],baseX:.50,baseY:.82},{x:[.315,.655],y:[.32,.635],baseX:.50,baseY:.82},{x:[.33,.66],y:[.29,.615],baseX:.50,baseY:.82},{x:[.335,.68],y:[.285,.60],baseX:.50,baseY:.82}][ci];el.style.left='calc('+slotData.x[pi%2]*100+'% - '+slotData.baseX*12+'cqw)';el.style.top='calc('+slotData.y[pi<2?0:1]*100+'% - '+slotData.baseY*12+'cqw)';document.querySelector('.well-'+colors[ci]).append(el);}else cell.append(el)}));activate()}
function activate(){[...document.querySelectorAll('.pd')].sort((a,b)=>Number(a.dataset.player)-Number(b.dataset.player)).forEach((el,i)=>{el.classList.toggle('active',started&&turn===i);el.querySelector('b').textContent=i===humanColor?'Tú':names[i];el.querySelector('.player-progress').innerHTML=pieces[i].map(p=>p===56?'<span class="goal-pawn '+colors[i]+'"><span class="pawn-art"><img src="assets/ludo-pawns-standing.webp?v=25" alt="Ficha completada"></span></span>':'<span class="goal-empty">○</span>').join('')});diceEls.forEach((el,i)=>el.disabled=!(started&&phase==='roll'&&turn===humanColor&&i===turn))}
function stopClock(){if(dragging){dragging.target.classList.remove('drop-target');dragging.ghost?.remove();dragging=null;}clearInterval(clock);clock=null;document.querySelectorAll('.player-timer').forEach(el=>el.textContent='')}
function startClock(){stopClock();seconds=10;const badge=document.querySelector('[data-player="'+humanColor+'"] .player-timer');badge.textContent='10';badge.style.setProperty('--remaining','100%');clock=setInterval(()=>{seconds--;badge.textContent=String(seconds);badge.style.setProperty('--remaining',(seconds*10)+'%');if(seconds<=0){stopClock();if(phase==='roll')rollDie();else if(phase==='move')move(legal(turn,last)[0])}},1000)}
function beginTurn(){if(!started)return;phase='roll';last=0;document.querySelector('#boardWrap').classList.remove('throwing');diceEls.forEach(el=>el.classList.remove('rolling'));document.querySelector('#throwDie').classList.remove('rolling');document.querySelector('#turnTimer').textContent='';render();status.textContent=turn===humanColor?'Tu turno · toca tu dado.':'Turno de '+names[turn];if(turn===humanColor){playSound('turn');startClock();}else later(rollDie,850)}
function later(fn,ms){const g=generation;setTimeout(()=>{if(started&&g===generation)fn()},ms)}
function next(extra=false){stopClock();if(!extra){turn=(turn+1)%4;sixes=0}beginTurn()}
function rollDie(){if(phase!=='roll'||!started)return;stopClock();phase='rolling';playSound('dice');status.textContent=(turn===humanColor?'Estás lanzando':names[turn]+' está lanzando')+' el dado…';document.querySelector('#turnTimer').textContent='';activate();const el=diceEls[turn],value=randomDie();el.classList.add('rolling');document.querySelector('#boardWrap').classList.add('throwing');const big=document.querySelector('#throwDie');showDie(value,big);big.classList.add('rolling');later(()=>{el.classList.remove('rolling');big.classList.remove('rolling');document.querySelector('#boardWrap').classList.remove('throwing');showDie(value,el);last=value;if(value===6)playSound('six');sixes=value===6?sixes+1:0;if(sixes===3){status.textContent='Tres 6 seguidos · pasa el turno.';later(()=>next(),900);return}const moves=legal(turn,value);if(!moves.length){status.textContent=names[turn]+' sacó '+value+' · sin movimiento.';later(()=>next(value===6),900);return}phase='move';render();status.textContent=(turn===humanColor?'Sacaste ':names[turn]+' sacó ')+value+' · '+(turn===humanColor?'elige una ficha: tócala o arrástrala al destino iluminado.':'moviendo ficha.');if(turn===humanColor)startClock();else later(()=>{const hand=pieces[turn];const choice=moves.find(i=>hand[i]<0)??moves.reduce((a,b)=>hand[b]>hand[a]?b:a);move(choice)},550)},1100)}
function move(i){if(phase!=='move'||!legal(turn,last).includes(i))return;stopClock();playSound('select');phase='animating';activate();const ci=turn,initial=pieces[ci][i],dest=initial<0?0:initial+last;let current=initial;function step(){current=initial<0?0:current+1;pieces[ci][i]=current;playSound('tile');render();status.textContent=initial<0?'Ficha en la salida.':(ci===humanColor?'Tu ficha':names[ci])+' · paso '+(current-initial)+' de '+last;if(current<dest){later(step,280);return}let captured=false;if(dest<=50){const square=(starts[ci]+dest)%52;if(!safe.has(square))pieces.forEach((hand,j)=>{if(j===ci)return;hand.forEach((p,k)=>{if(p>=0&&p<=50&&(starts[j]+p)%52===square){hand[k]=-1;captured=true}})})}render();if(dest===56)playSound('home');if(captured)playSound('capture');if(pieces[ci].every(p=>p===56)){started=false;phase='finished';stopClock();status.textContent=(ci===humanColor?'¡Ganaste!':'¡Ganó '+names[ci]+'!')+' Las cuatro fichas llegaron.';document.querySelector('#turnTimer').textContent='🏆';activate();showVictory(ci);return}status.textContent=captured?'¡Captura! La ficha rival vuelve a casa.':dest===56?'¡Ficha en la meta!':last===6?'¡Un 6! Vuelve a lanzar.':'Movimiento completado · '+last+' pasos.';later(()=>next(last===6||captured||dest===56),650)}step()}
diceEls.forEach((el,i)=>{showDie(1,el);el.onclick=()=>{if(i===turn&&turn===humanColor)rollDie()}});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{selectedTier=b.dataset.tier;document.querySelectorAll('[data-tier]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#setupHint').textContent='Sala elegida · puedes empezar.'});
document.querySelector('#startGame').onclick=()=>{if(!selectedTier){document.querySelector('#setupHint').textContent='Elige Principiante, Clásica o VIP para comenzar.';return}document.querySelector('#victoryOverlay').classList.add('hidden');generation++;pieces=colors.map(()=>Array(4).fill(-1));humanColor=3;turn=humanColor;sixes=0;started=true;document.querySelector('#setup').classList.add('hidden');document.querySelector('#boardWrap').classList.remove('hidden');document.querySelector('#gamePanel').classList.remove('hidden');document.querySelector('#playersTop').classList.remove('hidden');document.querySelector('#playersBottom').classList.remove('hidden');beginTurn()};
document.querySelector('#menuButton').onclick=()=>document.querySelector('#gameMenu').showModal();document.querySelector('#closeMenu').onclick=()=>document.querySelector('#gameMenu').close();document.querySelector('#newGame').onclick=()=>{generation++;started=false;phase='idle';stopClock();document.querySelector('#gameMenu').close();document.querySelector('#setup').classList.remove('hidden');document.querySelector('#boardWrap').classList.add('hidden');document.querySelector('#gamePanel').classList.add('hidden');document.querySelector('#playersTop').classList.add('hidden');document.querySelector('#playersBottom').classList.add('hidden');document.querySelector('#boardWrap').classList.remove('throwing')};
document.querySelector('#settingsButton').onclick=()=>document.querySelector('#rulesDialog').showModal();document.querySelector('#closeRules').onclick=()=>document.querySelector('#rulesDialog').close();document.querySelector('#friendsButton').onclick=()=>{document.querySelector('#noticeText').textContent='Esta partida se juega contra tres jugadores automáticos. La conexión con amigos todavía no está disponible.';document.querySelector('#notice').showModal()};document.querySelector('#addCoins').onclick=()=>{document.querySelector('#noticeText').textContent='Saldo de demostración: 10,000 monedas virtuales. Las recargas todavía no están disponibles.';document.querySelector('#notice').showModal()};document.querySelector('#closeNotice').onclick=()=>document.querySelector('#notice').close();render();

document.querySelectorAll('.pd').forEach(card=>card.onclick=()=>{if(Number(card.dataset.player)===turn&&turn===humanColor)rollDie()});status.onclick=()=>{if(turn===humanColor)rollDie()};


function enableDrag(el,ci,pi){
 el.onpointerdown=e=>{if(phase!=='move'||turn!==humanColor||!legal(ci,last).includes(pi))return;e.preventDefault();el.setPointerCapture?.(e.pointerId);const p=pieces[ci][pi],dest=p<0?0:p+last,rc=dest===56?lanes[ci][5]:position(ci,dest,pi),target=board.children[rc[0]*15+rc[1]];target.classList.add('drop-target');dragging={el,ci,pi,target,startX:e.clientX,startY:e.clientY,moved:false,ghost:null};};
 el.onpointermove=e=>{const d=dragging;if(!d||d.el!==el)return;if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<7&&!d.moved)return;d.moved=true;if(!d.ghost){d.ghost=el.cloneNode(true);d.ghost.className='piece '+colors[ci]+' drag-ghost';document.body.append(d.ghost)}d.ghost.style.left=(e.clientX-24)+'px';d.ghost.style.top=(e.clientY-36)+'px';};
 el.onpointerup=e=>{const d=dragging;if(!d||d.el!==el)return;dragging=null;d.target.classList.remove('drop-target');d.ghost?.remove();el.dataset.dragged='1';setTimeout(()=>delete el.dataset.dragged,0);const r=d.target.getBoundingClientRect(),inside=e.clientX>=r.left-12&&e.clientX<=r.right+12&&e.clientY>=r.top-12&&e.clientY<=r.bottom+12;if(!d.moved||inside)move(pi);else status.textContent='Suelta la ficha en la casilla iluminada. El dado indica '+last+' pasos.';};
 el.onpointercancel=()=>{dragging?.target.classList.remove('drop-target');dragging?.ghost?.remove();dragging=null;};
}

function playSound(name){try{window.DCSound?.[name]?.()}catch{}}
function showVictory(ci){const overlay=document.querySelector('#victoryOverlay');overlay.classList.remove('hidden');document.querySelector('#victoryTitle').textContent=ci===humanColor?'¡Ganaste!':'Ganó '+names[ci];playSound(ci===humanColor?'win':'home');const canvas=document.querySelector('#fireworks'),ctx=canvas.getContext('2d');if(!ctx)return;const width=canvas.width=innerWidth,height=canvas.height=innerHeight,particles=[],start=performance.now();let previousBurst=-1000;function frame(now){if(overlay.classList.contains('hidden'))return;ctx.clearRect(0,0,width,height);if(now-start<5500&&now-previousBurst>550){previousBurst=now;const x=width*(.15+Math.random()*.7),y=height*(.1+Math.random()*.5),hue=Math.random()*360;for(let i=0;i<60;i++){const angle=i*Math.PI*2/60,speed=1+Math.random()*3;particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:65,hue})}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.035;p.life--;ctx.fillStyle='hsla('+p.hue+',90%,70%,'+(p.life/65)+')';ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fill();if(p.life<=0)particles.splice(i,1)}if(particles.length||now-start<5500)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
document.querySelector('#victoryContinue').onclick=()=>document.querySelector('#victoryOverlay').classList.add('hidden');document.querySelector('#victoryRestart').onclick=()=>{document.querySelector('#victoryOverlay').classList.add('hidden');document.querySelector('#newGame').click()};

const soundToggle=document.querySelector('#soundToggle');let ludoMuted=false;soundToggle.onclick=()=>{ludoMuted=!ludoMuted;window.DCSound?.setMuted(ludoMuted);soundToggle.textContent=ludoMuted?'Sonido: desactivado':'Sonido: activado';soundToggle.setAttribute('aria-pressed',String(!ludoMuted));if(!ludoMuted)playSound('select')};
